### ISSUE TITLE
I cant login!

### ISSUE THREAD

**Issue by anshangPro** [leoding86/pixiv-omina#36] opened 2020-09-25 16:44 UTC
with proxy opening,i tried serval times,but all in vain,
it just say that i have loged in and please refresh the page while the program still ask me to login.

if i close the page and reopen it,it will be left blank until i delete the data in %AppData%\Roaming\Pixiv Omina

PLEASE FIX IT!
THE LOGIN SYSTEM MUST BE WRONG!

**Comment by leoding86** [comment] 2020-09-27 08:25
I can't reproduce the issue. Which type proxy do you use?

**Comment by anshangPro** [comment] 2020-09-29 11:27
> I can't reproduce the issue. Which type proxy do you use?

i used the ShadowsocksR.
it just show me a blank page and nothing after logining.
maybe because pixiv updated their policy?

**Comment by leoding86** [comment] 2020-09-29 12:49
Could you take a screenshot of your proxy settings?

**Comment by anshangPro** [comment] 2020-09-30 04:59
![image](https://user-images.githubusercontent.com/65436468/94644691-8fb67880-031c-11eb-8e64-1ad00c3a62c2.png)
![image](https://user-images.githubusercontent.com/65436468/94644699-9513c300-031c-11eb-923b-ae0ccf451978.png)
It suddenly works.
I dont know why.

**Comment by leoding86** [comment] 2020-09-30 07:12
I think the proxy settings is fine. I'll keep mind on this issue. You can reopen it when you think it's necessary, I close it for now.

**Closed as completed by leoding86** 2020-09-30 07:12 UTC
Labels: question
